# MCTS sponsorship and funding options
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [MCTS]
open_collective: mcts
polar: mcts
buy_me_a_coffee: mcts
